:Author: Ben Martinez-Bateman
:Email: ben@alwaysblank.org
:toc: macro
:toclevels: 3
:toc-title:
:sectanchors:
:sectlinks:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: ðŸ’¡
:note-caption: â„¹
:important-caption: â—
:caution-caption: ðŸ”¥
:warning-caption: âš 
endif::[]

= Cloudinary

This provides some shortcodes and filters for generating Cloudinary URLs.

toc::[]

== Usage

Since the shortcodes this plugin provides are pretty genericlly named, it's recommended that you namespace them:

[source,javascript]
----
conf.namespace('cl_', () => {
    conf.addPlugin(cloudinary)
});
----

### Configuration

The plugin accepts several configuration options.

- `name` - This is the cloud name for your Cloudinary account.
    You _must_ pass this, or the plugin won't work.
- `transforms` - *optional* This is a set of transforms that will be applied to _all_ images generated by the plugin.
    It assumes an array in the manner of the `transformation` argument on the link:https://cloudinary.com/documentation/node_integration[node SDK].
    (The node SDK powers most of what this plugin does.)
- `defaults` - *optional* Adjust the defaults for various settings in the plugin.
    - `width` - [`768`] *optional* The fallback width used for an image if the plugin isn't given one.


== Shortcodes

Shortcodes are kind of like functions--they take in some arguments and return a string.

For this shortcodes, pass arguments as a JS object:

[source,html]
----
{% cl_image { path: 'folder/image.jpg', transforms: 'w_400' } %}
----

This allows us to allow for many arguments without requiring all of them to be specified.

[TIP]
====
Set up commonly-used sets of arguments in your frontmatter or elsewhere so you can easily reused them!
====

=== url

This will return a url, appropriately constructed.

**Arguments**

- `path` - This is the path on cloudinary to the item you want, i.e. `folder/image.jpg`
- `transforms` - Any transforms you'd like to apply to this item.

=== image

This will return an entire image element.

**Arguments**

- `path` - This is the path on cloudinary to the item you want, i.e. `folder/image.jpg`
- `transforms` - Any transforms you'd like to apply to this item.
    These transforms will be applied to all urls in this image (the `src` and `srcset`).
- `alt`
- `title`
- `size` - The base size for this image.
- `sizes` - A string describing the sizing.
- `srcset` - Either a string (which will be reproduced as-is) or an array of integers, which will be used as widths.
- `css` - This would normally be called `class` but JavaScript doesn't like that.
    A list of classes for this element.
- `attrs` - Any other HTML attributes you want on this element, pass as an array of arrays.
    For boolean attributes, just use an array with a single value.

== Filters

Filters take in a value, do something to it, and return it.
They're especially useful because they can be strung together to run several operations on a value in sequence.

[WARNING]
====
This plugin is primarily intended for use with nunjucks
(or `.njk`)
templates.
The filters are defined as universal, and should work in Liquid and 11ty.js templates, but haven't been tested.
====

=== url

The `url` filter behaves essentially the same as the shortcode, except that it takes it's parameters a bit differently:

[source,jinja]
----
{{ 'image.jpg' | img([{ width: 470 }]) }}
----